# Generated by Django 5.2.6 on 2025-09-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("profession", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="testimonials/")),
                ("message", models.TextField()),
            ],
        ),
    ]
