# Generated by Django 5.2.6 on 2025-09-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("email_address", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("submit", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
