# Generated by Django 5.2.6 on 2025-09-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="phone_number",
        ),
    ]
