# Generated by Django 5.2.6 on 2025-09-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="about_description",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="about_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="label",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="max_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="mini_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="photo",
        ),
        migrations.AddField(
            model_name="homepage",
            name="button_link",
            field=models.CharField(default="#booking", max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button_text",
            field=models.CharField(default="Book A Table", max_length=50),
        ),
        migrations.AddField(
            model_name="homepage",
            name="description",
            field=models.TextField(default="Default description text", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Hero section image",
                null=True,
                upload_to="hero_images/",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="title",
            field=models.CharField(default="Default description text", max_length=200),
            preserve_default=False,
        ),
    ]
