# Generated by Django 5.2.6 on 2025-09-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Welcome to Restoran", max_length=200),
                ),
                ("subtitle", models.CharField(blank=True, max_length=200, null=True)),
                ("description1", models.TextField(blank=True, null=True)),
                ("description2", models.TextField(blank=True, null=True)),
                ("years_experience", models.PositiveIntegerField(default=15)),
                ("popular_chefs", models.PositiveIntegerField(default=50)),
                ("read_more_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
